spring:
  application:
    name: gitlab-telegram-integration
  datasource:
    driver-class-name: org.postgresql.Driver
    password: myservice
    url: jdbc:postgresql://localhost/gitlabdatabase
    username: myservice
